name: CI

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run typechecks
        run: pnpm -r exec tsc --noEmit

      - name: Run tests
        run: pnpm -r test
